export const GET_MOVEIS_START = "GET_MOVEIS_START";
export const GET_MOVEIS_SUCCESS = "GET_MOVEIS_SUCCESS";
export const GET_MOVEIS_FAILED = "GET_MOVEIS_FAILED";

export const GET_MOVEI_BY_ID_START = "GET_MOVEI_BY_ID_START";
export const GET_MOVEI_BY_ID_SUCCESS = "GET_MOVEI_BY_ID_SUCCESS";
export const GET_MOVEI_BY_ID_FAILED = "GET_MOVEI_BY_ID_FAILED";